// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

/// <reference types="node" />

import "dotenv/config";
import path from "node:path"
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  // diz que o arquivo de banco de dados esta na pasta prisma e se chama schema.prisma
  schema: path.join('prisma', 'schema.prisma'),
  migrations: {
    path: path.join('prisma', 'migrations'),
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
